<?php
namespace App\Services\Assets;

if(!defined('PREFIX_FILENAME_NUSANTARA_IMAGE')) define('PREFIX_FILENAME_NUSANTARA_IMAGE', 'img_nusantara_');

if(!defined('MAX_IMAGE_SIZE')) define('MAX_IMAGE_SIZE', 1000);

/**
 * Static Page
 */
if(!defined('LOGO_SIZE')) define('LOGO_SIZE', 1000);
if(!defined('LOGO_WIDTH')) define('LOGO_WIDTH', 701);
if(!defined('LOGO_HEIGHT')) define('LOGO_HEIGHT', 169);


if(!defined('FAVICON_SIZE')) define('FAVICON_SIZE', 500);
if(!defined('FAVICON_WIDTH')) define('FAVICON_WIDTH', 64);
if(!defined('FAVICON_HEIGHT')) define('FAVICON_HEIGHT', 64);


if(!defined('OG_IMAGE_SIZE')) define('OG_IMAGE_SIZE', 1000);
if(!defined('OG_IMAGE_WIDTH')) define('OG_IMAGE_WIDTH', 1200);
if(!defined('OG_IMAGE_HEIGHT')) define('OG_IMAGE_HEIGHT', 315);

/*
* Main Banner
*/
if(!defined('MAIN_BANNER_SIZE')) define('MAIN_BANNER_SIZE', 1000);
if(!defined('MAIN_BANNER_WIDTH')) define('MAIN_BANNER_WIDTH', 1350);
if(!defined('MAIN_BANNER_HEIGHT')) define('MAIN_BANNER_HEIGHT', 660);

/*
* Branch Officce Banner
*/
if(!defined('BRANCH_OFFICE_THUMBNAIL_SIZE')) define('BRANCH_OFFICE_THUMBNAIL_SIZE', 1000);
if(!defined('BRANCH_OFFICE_THUMBNAIL_WIDTH')) define('BRANCH_OFFICE_THUMBNAIL_WIDTH', 290);
if(!defined('BRANCH_OFFICE_THUMBNAIL_HEIGHT')) define('BRANCH_OFFICE_THUMBNAIL_HEIGHT', 193);
if(!defined('BRANCH_OFFICE_IMAGES_WIDTH')) define('BRANCH_OFFICE_IMAGES_WIDTH', 1920);
if(!defined('BRANCH_OFFICE_IMAGES_HEIGHT')) define('BRANCH_OFFICE_IMAGES_HEIGHT', 1080);

/*
* Awards
*/
if(!defined('AWARDS_THUMBNAIL_SIZE')) define('AWARDS_THUMBNAIL_SIZE', 1000);
if(!defined('AWARDS_THUMBNAIL_WIDTH')) define('AWARDS_THUMBNAIL_WIDTH', 290);
if(!defined('AWARDS_THUMBNAIL_HEIGHT')) define('AWARDS_THUMBNAIL_HEIGHT', 193);
if(!defined('AWARDS_IMAGES_WIDTH')) define('AWARDS_IMAGES_WIDTH', 1920);
if(!defined('AWARDS_IMAGES_HEIGHT')) define('AWARDS_IMAGES_HEIGHT', 1080);

/*
* Promotion
*/
if(!defined('PROMOTION_IMAGE_SIZE')) define('PROMOTION_IMAGE_SIZE', 1000);
if(!defined('PROMOTION_CATEGORI_WIDTH')) define('PROMOTION_CATEGORI_WIDTH', 1179);
if(!defined('PROMOTION_CATEGORI_HEIGHT')) define('PROMOTION_CATEGORI_HEIGHT', 500);

if(!defined('PROMOTION_THUMBNAIL_WIDTH')) define('PROMOTION_THUMBNAIL_WIDTH', 940);
if(!defined('PROMOTION_THUMBNAIL_HEIGHT')) define('PROMOTION_THUMBNAIL_HEIGHT', 520);


if(!defined('PROMOTION_GALLERY_WIDTH')) define('PROMOTION_GALLERY_WIDTH', 771);
if(!defined('PROMOTION_GALLERY_HEIGHT')) define('PROMOTION_GALLERY_HEIGHT', 435);


if(!defined('PROMOTION_BANNER_IMAGES_WIDTH')) define('PROMOTION_BANNER_IMAGES_WIDTH', 1400);
if(!defined('PROMOTION_BANNER_IMAGES_HEIGHT')) define('PROMOTION_BANNER_IMAGES_HEIGHT', 568);


if(!defined('PROMOTION_IMAGES_WIDTH')) define('PROMOTION_IMAGES_WIDTH', 585);
if(!defined('PROMOTION_IMAGES_HEIGHT')) define('PROMOTION_IMAGES_HEIGHT', 327);

/**
 * EVENT AND SERVICES
 */
if(!defined('EVENT_AND_SERVICE_IMAGES_WIDTH')) define('EVENT_AND_SERVICE_IMAGES_WIDTH', 600);
if(!defined('EVENT_AND_SERVICE_IMAGES_HEIGHT')) define('EVENT_AND_SERVICE_IMAGES_HEIGHT', 400);

/**
 * EVENT AND SERVICES DETAIL
 */
if(!defined('EVENT_AND_SERVICE_IMAGES_DETAIL_WIDTH')) define('EVENT_AND_SERVICE_IMAGES_DETAIL_WIDTH', 900);
if(!defined('EVENT_AND_SERVICE_IMAGES_DETAIL_HEIGHT')) define('EVENT_AND_SERVICE_IMAGES_DETAIL_HEIGHT', 675);

/**
 * NEWS
 */
if(!defined('NEWS_THUMBNAIL_WIDTH')) define('NEWS_THUMBNAIL_WIDTH', 900);
if(!defined('NEWS_THUMBNAIL_HEIGHT')) define('NEWS_THUMBNAIL_HEIGHT', 675);
if(!defined('NEWS_IMAGES_DETAIL_WIDTH')) define('NEWS_IMAGES_DETAIL_WIDTH', 1400);
if(!defined('NEWS_IMAGES_DETAIL_HEIGHT')) define('NEWS_IMAGES_DETAIL_HEIGHT', 568);
